services:
  app:
    build: .
    container_name: geotracker-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "4000:4000" # your API port
      - "1883:1883" # expose MQTT broker port
    volumes:
      - ./:/usr/src/app:cached
      - node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://host.docker.internal:27017/geotracker
      - MQTT_HOST=0.0.0.0 # Mosca will listen on all interfaces
      - SERVER_IP=127.0.0.1 # your host system IP (for devices)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "npm install && npm run dev"
    networks:
      - geotracker-net

  
volumes:
  mongo-data:
  node_modules:

networks:
  geotracker-net:
    driver: bridge
