exports.dtcCodes = {
  P0000: "ISO/SAE Reserved",
  P0001: "Fuel Volume Regulator Control Circuit/Open",
  P0002: "Fuel Volume Regulator Control Circuit Range/Performance",
  P0003: "Fuel Volume Regulator Control Circuit Low",
  P0004: "Fuel Volume Regulator Control Circuit High",
  P0005: "Fuel Shutoff Valve A Control Circuit/Open",
  P0006: "Fuel Shutoff Valve A Control Circuit Low",
  P0007: "Fuel Shutoff Valve A Control Circuit High",
  P0008: "Engine Positions System Performance Bank 1",
  P0009: "Engine Position System Performance Bank 2",
  P000A: "A Camshaft Position Slow Response Bank 1",
  P000B: "B Camshaft Position Slow Response Bank 1",
  P000C: "A Camshaft Position Slow Response Bank 2",
  P000D: "B Camshaft Position Slow Response Bank 2",
  P000E: "Fuel Volume Regulator Control Exceeded Learning Limit",
  P000F: "Fuel System Over Pressure Relief Valve Activated",
  P0010: "A Camshaft Position Actuator Circuit (Bank 1)",
  P0011:
    "A Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)",
  P0012: "A Camshaft Position - Timing Over-Retarded (Bank 1)",
  P0013: "B Camshaft Position - Actuator Circuit (Bank 1)",
  P0014:
    "B Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)",
  P0015: "B Camshaft Position -Timing Over-Retarded (Bank 1)",
  P0016:
    "Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor A)",
  P0017:
    "Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor B)",
  P0018:
    "Crankshaft Position - Camshaft Position Correlation (Bank 2 Sensor A)",
  P0019:
    "Crankshaft Position - Camshaft Position Correlation (Bank 2 Sensor B)",
  P001A: "A Camshaft Profile Control Circuit/Open Bank 1",
  P001B: "A Camshaft Profile Control Circuit Low Bank 1",
  P001C: "A Camshaft Profile Control Circuit High Bank 1",
  P001D: "A Camshaft Profile Control Circuit/Open Bank 2",
  P001E: "A Camshaft Profile Control Circuit Low Bank 2",
  P001F: "A Camshaft Profile Control Circuit High Bank 2",
  P0020: "A Camshaft Position Actuator Circuit (Bank 2)",
  P0021:
    "A Camshaft Position - Timing Over-Advanced or System Performance (Bank 2)",
  P0022: "A Camshaft Position - Timing Over-Retarded (Bank 2)",
  P0023: "B Camshaft Position - Actuator Circuit (Bank 2)",
  P0024:
    "B Camshaft Position - Timing Over-Advanced or System Performance (Bank 2)",
  P0025: "B Camshaft Position - Timing Over-Retarded (Bank 2)",
  P0026: "Intake Valve Control Solenoid Circuit Range/Performance Bank 1",
  P0027: "Exhaust Valve Control solenoid Circuit Range/Performance Bank 1",
  P0028: "Intake valve Control Solenoid Circuit Range/Performance Bank 2",
  P0029: "Exhaust Valve Control Solenoid Circuit Range/Performance Bank 2",
  P002A: "B Camshaft Profile Control Circuit/Open Bank 1",
  P002B: "B Camshaft Profile Control Circuit Low Bank 1",
  P002C: "B Camshaft Profile Control Circuit High Bank 1",
  P002D: "B Camshaft Profile Control Circuit/Open Bank 2",
  P002E: "B Camshaft Profile Control Circuit Low Bank 2",
  P002F: "B Camshaft Profile Control Circuit High Bank 2",
  P0030: "HO2S Heater Control Circuit (Bank 1 Sensor 1)",
  P0031: "HO2S Heater Control Circuit Low (Bank 1 Sensor 1)",
  P0032: "HO2S Heater Control Circuit High (Bank 1 Sensor 1)",
  P0033: "Turbo Charger Bypass Valve Control Circuit",
  P0034: "Turbo Charger Bypass Valve Control Circuit Low",
  P0035: "Turbo Charger Bypass Valve Control Circuit High",
  P0036: "HO2S Heater Control Circuit (Bank 1 Sensor 2)",
  P0037: "HO2S Heater Control Circuit Low (Bank 1 Sensor 2)",
  P0038: "HO2S Heater Control Circuit High (Bank 1 Sensor 2)",
  P0039: "Turbo/Super Charger Bypass Valve Control Circuit Range/Performance",
  P003A:
    "Turbocharger/Supercharger Boost Control A Position Exceeded Learning Limit",
  P003B:
    "Turbocharger/Supercharger Boost Control B Position Exceeded Learning Limit",
  P003C: "A Camshaft Profile Control Performance/Stuck Off Bank 1",
  P003D: "A Camshaft Profile Control Stuck On Bank 1",
  P003E: "A Camshaft Profile Control Performance/Stuck Off Bank 2",
  P003F: "A Camshaft Profile Control Stuck On Bank 2",
  P0040: "Upstream Oxygen Sensors Swapped From Bank To Bank",
  P0041: "Downstream Oxygen Sensors Swapped From Bank To Bank",
  P0042: "HO2S Heater Control Circuit (Bank 1 Sensor 3)",
  P0043: "HO2S Heater Control Circuit Low (Bank 1 Sensor 3)",
  P0044: "HO2S Heater Control Circuit High (Bank 1 Sensor 3)",
  P0045: "Turbocharger/Supercharger Boost Control A Circuit/Open",
  P0046: "Turbocharger/Supercharger Boost Control A Circuit Range/Performance",
  P0047: "Turbocharger/Supercharger Boost Control A Circuit Low",
  P0048: "Turbocharger/Supercharger Boost Control A Circuit High",
  P0049: "Turbocharger/Supercharger Turbine Overspeed",
  P004A: "Turbocharger/Supercharger Boost Control B Circuit/Open",
  P004B: "Turbocharger/Supercharger Boost Control B Circuit Range/Performance",
  P004C: "Turbocharger/Supercharger Boost Control B Circuit Low",
  P004D: "Turbocharger/Supercharger Boost Control B Circuit High",
  P004E:
    "Turbocharger/Supercharger Boost Control A Circuit Intermittent/Erratic",
  P004F:
    "Turbocharger/Supercharger Boost Control B Circuit Intermittent/Erratic",
  P0050: "HO2S Heater Control Circuit (Bank 2 Sensor 1)",
  P0051: "HO2S Heater Control Circuit Low (Bank 2 Sensor 1)",
  P0052: "HO2S Heater Control Circuit High (Bank 2 Sensor 1)",
  P0053: "HO2S Heater Resistance (Bank 1, Sensor 1)",
  P0054: "HO2S Heater Resistance (Bank 1, Sensor 2)",
  P0055: "HO2S Heater Resistance (Bank 1, Sensor 3)",
  P0056: "HO2S Heater Control Circuit (Bank 2 Sensor 2)",
  P0057: "HO2S Heater Control Circuit Low (Bank 2 Sensor 2)",
  P0058: "HO2S Heater Control Circuit High (Bank 2 Sensor 2)",
  P0059: "HO2S Heater Resistance (Bank 2, Sensor 1)",
  P005A: "B Camshaft Profile Control Performance/Stuck Off Bank 1",
  P005B: "B Camshaft Profile Control Stuck On Bank 1",
  P005C: "B Camshaft Profile Control Performance/Stuck Off Bank 2",
  P005D: "B Camshaft Profile Control Stuck On Bank 2",
  P005E: "Turbocharger/Supercharger Boost Control B Supply Voltage Circuit Low",
  P005F:
    "Turbocharger/Supercharger Boost Control B Supply Voltage Circuit High",
  P0060: "HO2S Heater Resistance (Bank 2, Sensor 2)",
  P0061: "HO2S Heater Resistance (Bank 2, Sensor 3)",
  P0062: "HO2S Heater Control Circuit (Bank 2 Sensor 3)",
  P0063: "HO2S Heater Control Circuit Low (Bank 2 Sensor 3)",
  P0064: "HO2S Heater Control Circuit High (Bank 2 Sensor 3)",
  P0065: "Air Assisted Injector Control Range/Performance",
  P0066: "Air Assisted Injector Control Circuit or Circuit Low",
  P0067: "Air Assisted Injector Control Circuit High",
  P0068: "MAP/MAF - Throttle Position Correlation",
  P0069: "Manifold Absolute Pressure - Barometric Pressure Correlation",
  P006A: "MAP - Mass or Volume Air Flow Correlation Bank 1",
  P006B: "MAP - Exhaust Pressure Correlation",
  P006C: "MAP - Turbocharger/Supercharger Inlet Pressure Correlation",
  P006D:
    "Barometric Pressure - Turbocharger/Supercharger Inlet Pressure Correlation",
  P006E: "Turbocharger/Supercharger Boost Control A Supply Voltage Circuit Low",
  P006F:
    "Turbocharger/Supercharger Boost Control A Supply Voltage Circuit High",
  P0070: "Ambient Air Temperature Sensor Circuit",
  P0071: "Ambient Air Temperature Sensor Range/Performance",
  P0072: "Ambient Air Temperature Sensor Circuit Low Input",
  P0073: "Ambient Air Temperature Sensor Circuit High Input",
  P0074: "Ambient Air Temperature Sensor Circuit Intermittent",
  P0075: "Intake Valve Control Solenoid Circuit (Bank 1)",
  P0076: "Intake Valve Control Solenoid Circuit Low (Bank 1)",
  P0077: "Intake Valve Control Solenoid Circuit High (Bank 1)",
  P0078: "Exhaust Valve Control Solenoid Circuit (Bank 1)",
  P0079: "Exhaust Valve Control Solenoid Circuit Low (Bank 1)",
  P007A: "Charge Air Cooler Temperature Sensor Circuit Bank 1",
  P007B:
    "Charge Air Cooler Temperature Sensor Circuit Range/Performance Bank 1",
  P007C: "Charge Air Cooler Temperature Sensor Circuit Low Bank 1",
  P007D: "Charge Air Cooler Temperature Sensor Circuit High Bank 1",
  P007E:
    "Charge Air Cooler Temperature Sensor Circuit Intermittent/Erratic Bank 1",
  P007F: "Charge Air Cooler Temperature Sensor Bank1/Bank2 Correlation",
  P0080: "Exhaust Valve Control Solenoid Circuit High (Bank 1)",
  P0081: "Intake valve Control Solenoid Circuit (Bank 2)",
  P0082: "Intake Valve Control Solenoid Circuit Low (Bank 2)",
  P0083: "Intake Valve Control Solenoid Circuit High (Bank 2)",
  P0084: "Exhaust Valve Control Solenoid Circuit (Bank 2)",
  P0085: "Exhaust Valve Control Solenoid Circuit Low (Bank 2)",
  P0086: "Exhaust Valve Control Solenoid Circuit High (Bank 2)",
  P0087: "Fuel Rail/System Pressure - Too Low",
  P0088: "Fuel Rail/System Pressure - Too High",
  P0089: "Fuel Pressure Regulator 1 Performance",
  P008A: "Low Pressure Fuel System Pressure - Too Low",
  P008B: "Low Pressure Fuel System Pressure - Too High",
  P008C: "Fuel Cooler Pump Control Circuit Open",
  P008D: "Fuel Cooler Pump Control Circuit Low",
  P008E: "Fuel Cooler Pump Control Circuit High",
  P008F: "Engine Coolant Temperature/Fuel Temperature Correlation",
  P0090: "Fuel Pressure Regulator 1 Control Circuit",
  P0091: "Fuel Pressure Regulator 1 Control Circuit Low",
  P0092: "Fuel Pressure Regulator 1 Control Circuit High",
  P0093: "Fuel System Leak Detected - Large Leak",
  P0094: "Fuel System Leak Detected - Small Leak",
  P0095: "Intake Air Temperature Sensor 2 Circuit Bank 1",
  P0096: "Intake Air Temperature Sensor 2 Circuit Range/Performance Bank 1",
  P0097: "Intake Air Temperature Sensor 2 Circuit Low Bank 1",
  P0098: "Intake Air Temperature Sensor 2 Circuit High Bank 1",
  P0099: "Intake Air Temperature Sensor 2 Circuit Intermittent/Erratic Bank 1",
  P009A: "Intake Air Temperature/Ambient Air Temperature Correlation",
  P009B: "Fuel Pressure Relief Control Circuit/Open",
  P009C: "Fuel Pressure Relief Control Circuit Low",
  P009D: "Fuel Pressure Relief Control Circuit High",
  P009E: "Fuel Pressure Relief Control Performance/Stuck Off",
  P009F: "Fuel Pressure Relief Control Stuck On",
  P00A0: "Charge Air Cooler Temperature Sensor Circuit Bank 2",
  P00A1:
    "Charge Air Cooler Temperature Sensor Circuit Range/Performance Bank 2",
  P00A2: "Charge Air Cooler Temperature Sensor Circuit Low Bank 2",
  P00A3: "Charge Air Cooler Temperature Sensor Circuit High Bank 2",
  P00A4:
    "Charge Air Cooler Temperature Sensor Circuit Intermittent/Erratic Bank 2",
  P00A5: "Intake Air Temperature Sensor 2 Circuit Bank 2",
  P00A6: "Intake Air Temperature Sensor 2 Circuit Range/Performance Bank 2",
  P00A7: "Intake Air Temperature Sensor 2 Circuit Low Bank 2",
  P00A8: "Intake Air Temperature Sensor 2 Circuit High Bank 2",
  P00A9: "Intake Air Temperature Sensor 2 Circuit Intermittent/Erratic Bank 2",
  P00AA: "Intake Air Temperature Sensor 1 Circuit Bank 2",
  P00AB: "Intake Air Temperature Sensor 1 Circuit Range/Performance Bank 2",
  P00AC: "Intake Air Temperature Sensor 1 Circuit Low Bank 2",
  P00AD: "Intake Air Temperature Sensor 1 Circuit High Bank 2",
  P00AE: "Intake Air Temperature Sensor 1 Circuit Intermittent/Erratic Bank 2",
  P00AF: "Turbocharger/Supercharger Boost Control A Module Performance",
  P00B0: "Turbocharger/Supercharger Boost Control B Module Performance",
  P00B1: "Radiator Coolant Temperature Sensor Circuit",
  P00B2: "Radiator Coolant Temperature Sensor Circuit Range/Performance",
  P00B3: "Radiator Coolant Temperature Sensor Circuit Low",
  P00B4: "Radiator Coolant Temperature Sensor Circuit High",
  P00B5: "Radiator Coolant Temperature Sensor Circuit Intermittent/Erratic",
  P00B6: "Radiator Coolant Temperature/Engine Coolant Temperature Correlation",
  P00B7: "Engine Coolant Flow Low/Performance",
  P00B8: "MAP - Mass or Volume Air Flow Correlation Bank 2",
  P00B9: "Low Pressure Fuel System Pressure - Too Low, Low Ambient Temperature",
  P00BA: "Low Fuel Pressure - Forced Limited Power",
  P00BB: "Fuel Injector Insufficient Flow - Forced Limited Power",
  P00BC:
    "Mass or Volume Air Flow A Circuit Range/Performance - Air Flow Too Low",
  P00BD:
    "Mass or Volume Air Flow A Circuit Range/Performance - Air Flow Too High",
  P00BE:
    "Mass or Volume Air Flow B Circuit Range/Performance - Air Flow Too Low",
  P00BF:
    "Mass or Volume Air Flow B Circuit Range/Performance - Air Flow Too High",
  P00C0: "-",
  P00FF: "ISO/SAE Reserved",
};
