name: GeoWise CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Skip tests
        run: echo "No tests yet"

      - name: Build Angular project
        run: npm run build

      - name: Build Docker image
        run: docker build -t geotracker-app .